/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'kevinjom' at '14-8-25 下午11:17' with Gradle 1.11
 *
 * @author kevinjom, @date 14-8-25 下午11:17
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
